"""add kolom tambahan seperti sistolik, riwayat penyakit, dll

Revision ID: 33fb7eeca03f
Revises: 
Create Date: 2025-08-08 09:08:03.980968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33fb7eeca03f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistolik', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('diastolik', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('kategori_tekanan_darah', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('riwayat_penyakit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('riwayat_merokok', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('aspek_psikologis', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.Float(), nullable=True))
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('usia',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('jenis_kelamin',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('berat_badan',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('tinggi_badan',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('bmi',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('pesan',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('pesan',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('diagnosa', schema=None) as batch_op:
        batch_op.alter_column('bmi',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('tinggi_badan',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('berat_badan',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('jenis_kelamin',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('usia',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('risk_score')
        batch_op.drop_column('aspek_psikologis')
        batch_op.drop_column('riwayat_merokok')
        batch_op.drop_column('riwayat_penyakit')
        batch_op.drop_column('kategori_tekanan_darah')
        batch_op.drop_column('diastolik')
        batch_op.drop_column('sistolik')

    # ### end Alembic commands ###
